name: Deploy Go Game to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Go Game for GitHub Pages
        run: npx nx build go-game --prod
        env:
          GITHUB_PAGES: true

      - name: Debug - List build outputs
        run: |
          echo "=== Root dist directory ==="
          ls -la dist/ || echo "No dist directory found"
          echo "=== Apps directory ==="
          ls -la apps/ || echo "No apps directory found"
          echo "=== Go-game app directory ==="
          ls -la apps/go-game/ || echo "No go-game directory found"
          echo "=== Go-game dist directory ==="
          ls -la apps/go-game/dist/ || echo "No go-game/dist directory found"
          echo "=== Find all dist directories ==="
          find . -name "dist" -type d
          echo "=== Find all HTML files ==="
          find . -name "*.html" -type f

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/go-game/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
